import Head from 'next/head'
import { Button, Typography } from 'antd'
import { useAppStore } from '@/lib/store/store'
import { HomeView } from '@/components/organisms/home/HomeView'

export default function Home() {
  const { user } = useAppStore()

  return (
    <>
      <Head>
        <title>Profitline</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeView />
        <Button>Profitline</Button>
        <Typography color="primary">{user.name}</Typography>
      </main>
    </>
  )
}
